import type { DefinitionView, EvaluationView, VersionView } from "./api";
export const evaluation: EvaluationView = {
  id: "evaluation",
  prompt_version_id: "draft",
  evaluation_suite_id: "suite",
  evaluation_fingerprint: "f".repeat(64),
  model_configuration: { provider: "synthetic-test-provider" },
  status: "succeeded",
  case_results: [{ id: "synthetic", passed: true }],
  metrics: { passed: 1 },
  passed: true,
  error_key: null,
  started_at: "2026-10-03T00:00:00Z",
  ended_at: "2026-10-03T00:00:01Z",
};
export const definition: DefinitionView = {
  id: "definition",
  definition_key: "question_generator/practice_generate",
  agent_key: "question_generator",
  scene_key: "practice_generate",
  template_kind: "task",
  display_name: "练习题目生成",
  description: "合成测试定义",
  runtime_status: "enabled",
  active_version_id: "active-new",
  created_at: "2026-10-03T00:00:00Z",
  updated_at: "2026-10-03T00:00:00Z",
  contract_sha256: "c".repeat(64),
  registered_contract: { tools: [] },
};
export const draft: VersionView = {
  id: "draft",
  definition_id: "definition",
  version: 3,
  revision: 2,
  status: "draft",
  content_sha256: "d".repeat(64),
  content: "合成旧正文",
  change_description: "合成变更",
  base_active_version_id: "active-old",
  rollback_from_version_id: null,
  created_at: "2026-10-03T00:00:00Z",
  published_at: null,
  variables: [],
  dependencies: [],
  latest_evaluation: evaluation,
};
