import type { KnowledgeCardView, WeaknessView } from "./api";

export const syntheticCard: KnowledgeCardView = {
  config: {
    topic: "合成知识概念",
    source_mode: "general",
    foundation: "know_concept",
    depth: "systematic",
  },
  id: "card-1",
  explanation_id: "explanation-1",
  version: 1,
  parent_version: null,
  foundation: "know_concept",
  depth: "systematic",
  preferred_language: "zh-CN",
  source_mode: "general",
  source_available: true,
  created_at: "2026-10-03T00:00:00Z",
  concept: "合成知识概念",
  applications: ["合成适用场景"],
  principles: ["合成执行原理"],
  examples: [{ title: "合成示例", content: "合成示例正文" }],
  misconceptions: ["合成误区"],
  exercises: [{ question: "合成理解练习？", self_check_points: ["合成自查要点"] }],
  citations: [],
};
export const syntheticWeakness: WeaknessView = {
  id: "weakness-1",
  title: "合成知识点",
  domain: "合成领域",
  tags: ["合成标签"],
  severity: "medium",
  decision: "confirmed",
  mastery_state: "to_learn",
  version: 2,
  evidence_sufficient: true,
  evidence_count: 1,
  available_evidence_count: 1,
  source_available: true,
  policy_version: "practice_weakness_v1",
  explanation_id: "explanation-1",
  active_card_version: 1,
  run: null,
  source_mode: "materials",
  knowledge_base_id: "base-1",
  file_ids: ["file-1"],
  created_at: "2026-10-03T00:00:00Z",
  updated_at: "2026-10-03T00:00:00Z",
};
