"""集中导入当前真实模型，供 Alembic 发现元数据。"""

from xuemian_ai.accounts.models import AuthAuditEvent, AuthSession, User
from xuemian_ai.agent_runs.models import AgentRun
from xuemian_ai.ai_quality.models import (
    AIQualityCase,
    AIQualityCaseEvent,
    DiagnosticAccessGrant,
    DiagnosticAudit,
    DiagnosticReplay,
    DiagnosticSnapshot,
)
from xuemian_ai.document_processing.models import (
    AIProcessingConsent,
    BackgroundTask,
    DocumentChunk,
    DocumentProcessingVersion,
    ProcessingAttempt,
    RetrievalTrace,
    VectorIndexProfile,
    VectorOperation,
)
from xuemian_ai.file_management.models import (
    FileAsset,
    FileAuditEvent,
    FileCleanupTask,
    FileDeletionTombstone,
    FileOrphanCandidate,
    FilePolicyVersion,
    KnowledgeBaseFile,
    StoredObject,
    UploadSession,
)
from xuemian_ai.knowledge_bases.models import KnowledgeBase
from xuemian_ai.learning.attachment_models import LearningAttachment
from xuemian_ai.learning.models import LearningConversation, LearningTurn
from xuemian_ai.learning_assets.models import (
    KnowledgeCardVersion,
    KnowledgeExplanation,
    KnowledgeRun,
    LearningEvidenceEvent,
    LearningReview,
    Weakness,
    WeaknessEvent,
    WeaknessEvidence,
)
from xuemian_ai.practice.models import (
    PracticeAnswer,
    PracticeAttempt,
    PracticeFeedback,
    PracticeGrade,
    PracticePlan,
    PracticeRevision,
    PracticeRun,
    PracticeSet,
    PracticeSubmission,
)
from xuemian_ai.profiles.models import UserProfile
from xuemian_ai.prompt_management.models import (
    PromptAuditEvent,
    PromptDefinition,
    PromptEvaluationRun,
    PromptEvaluationSuite,
    PromptVersion,
    PromptVersionDependency,
)

__all__ = [
    "AgentRun",
    "AIQualityCase",
    "AIQualityCaseEvent",
    "DiagnosticAccessGrant",
    "DiagnosticAudit",
    "DiagnosticReplay",
    "DiagnosticSnapshot",
    "PromptAuditEvent",
    "PromptDefinition",
    "PromptEvaluationRun",
    "PromptEvaluationSuite",
    "PromptVersion",
    "PromptVersionDependency",
    "KnowledgeCardVersion",
    "KnowledgeExplanation",
    "KnowledgeRun",
    "LearningEvidenceEvent",
    "LearningReview",
    "Weakness",
    "WeaknessEvent",
    "WeaknessEvidence",
    "PracticeSet",
    "PracticePlan",
    "PracticeRevision",
    "PracticeAttempt",
    "PracticeAnswer",
    "PracticeSubmission",
    "PracticeGrade",
    "PracticeRun",
    "PracticeFeedback",
    "LearningAttachment",
    "LearningConversation",
    "LearningTurn",
    "AIProcessingConsent",
    "BackgroundTask",
    "ProcessingAttempt",
    "VectorIndexProfile",
    "DocumentProcessingVersion",
    "DocumentChunk",
    "VectorOperation",
    "RetrievalTrace",
    "AuthAuditEvent",
    "AuthSession",
    "FileAsset",
    "FileAuditEvent",
    "FileCleanupTask",
    "FileDeletionTombstone",
    "FileOrphanCandidate",
    "FilePolicyVersion",
    "KnowledgeBase",
    "KnowledgeBaseFile",
    "StoredObject",
    "UploadSession",
    "User",
    "UserProfile",
]
