"""learning quick answer conversations

Revision ID: 20261002_02
Revises: 20261002_01
Create Date: 2026-10-02 21:35:21.462588
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261002_02"
down_revision: str | Sequence[str] | None = "20261002_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_conversations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=True),
        sa.Column("file_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(mode = 'materials' AND knowledge_base_id IS NOT NULL) OR "
            "(mode = 'general' AND knowledge_base_id IS NULL)",
            name="ck_learning_scope",
        ),
        sa.CheckConstraint("mode IN ('materials','general')", name="ck_learning_mode"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_learning_conversation_owner",
        "learning_conversations",
        ["user_id", "deleted_at", "updated_at"],
        unique=False,
    )
    op.create_table(
        "learning_turns",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("request_key", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("question_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("refused", sa.Boolean(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("trace_complete", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("feedback", sa.String(length=16), nullable=True),
        sa.Column("agent_key", sa.String(length=64), nullable=False),
        sa.Column("scene_key", sa.String(length=64), nullable=False),
        sa.Column("prompt_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feedback IS NULL OR feedback IN ('helpful','unhelpful')", name="ck_learning_feedback"
        ),
        sa.CheckConstraint(
            "status IN ('processing','succeeded','failed')", name="ck_learning_turn_status"
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["learning_conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_learning_turn_processing",
        "learning_turns",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.create_index(
        "uq_learning_turn_request",
        "learning_turns",
        ["conversation_id", "request_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_learning_turn_request", table_name="learning_turns")
    op.drop_index(
        "uq_learning_turn_processing",
        table_name="learning_turns",
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.drop_table("learning_turns")
    op.drop_index("ix_learning_conversation_owner", table_name="learning_conversations")
    op.drop_table("learning_conversations")
    # ### end Alembic commands ###
