"""Immutable prompt management and evaluation versions

Revision ID: 20261003_07
Revises: 20261003_06
Create Date: 2026-10-03 17:21:09.475594
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261003_07"
down_revision: str | Sequence[str] | None = "20261003_06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_definitions",
        sa.Column("definition_key", sa.String(length=100), nullable=False),
        sa.Column("agent_key", sa.String(length=64), nullable=False),
        sa.Column("scene_key", sa.String(length=64), nullable=False),
        sa.Column("template_kind", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("runtime_status", sa.String(length=16), nullable=False),
        sa.Column("active_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "runtime_status IN ('enabled','disabled')", name="ck_prompt_definition_status"
        ),
        sa.CheckConstraint(
            "template_kind IN ('shared','agent','task')", name="ck_prompt_definition_kind"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_key", "scene_key", "template_kind", name="uq_prompt_definition_scene"
        ),
        sa.UniqueConstraint("definition_key", name="uq_prompt_definition_key"),
    )
    op.create_table(
        "prompt_audit_events",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_evaluation_suites",
        sa.Column("agent_key", sa.String(length=64), nullable=False),
        sa.Column("scene_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("model_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_key", "scene_key", "version", name="uq_prompt_suite_version"),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("definition_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_description", sa.String(length=1000), nullable=False),
        sa.Column("base_active_version_id", sa.UUID(), nullable=True),
        sa.Column("rollback_from_version_id", sa.UUID(), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft','published','retired')", name="ck_prompt_version_status"
        ),
        sa.CheckConstraint("version >= 1 AND revision >= 1", name="ck_prompt_version_positive"),
        sa.ForeignKeyConstraint(
            ["base_active_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["definition_id"], ["prompt_definitions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["rollback_from_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("definition_id", "version", name="uq_prompt_version_number"),
    )
    op.create_index(
        "uq_prompt_version_published",
        "prompt_versions",
        ["definition_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "prompt_evaluation_runs",
        sa.Column("prompt_version_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_suite_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("model_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("case_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("error_key", sa.String(length=64), nullable=True),
        sa.Column("executed_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_suite_id"], ["prompt_evaluation_suites.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["executed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_version_dependencies",
        sa.Column("root_version_id", sa.UUID(), nullable=False),
        sa.Column("dependency_version_id", sa.UUID(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("dependency_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("slot IN ('global','agent')", name="ck_prompt_dependency_slot"),
        sa.CheckConstraint(
            "root_version_id <> dependency_version_id AND position >= 0",
            name="ck_prompt_dependency_identity",
        ),
        sa.ForeignKeyConstraint(
            ["dependency_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["root_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "root_version_id", "dependency_version_id", name="uq_prompt_dependency_version"
        ),
        sa.UniqueConstraint(
            "root_version_id", "slot", "position", name="uq_prompt_dependency_slot"
        ),
    )
    op.create_foreign_key(
        "fk_agent_run_prompt_version",
        "agent_runs",
        "prompt_versions",
        ["root_prompt_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_prompt_definition_active",
        "prompt_definitions",
        "prompt_versions",
        ["active_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # 数据库保护发布历史；不能只依赖某个HTTP编辑端点的检查。
    op.execute("""
    CREATE FUNCTION protect_prompt_version() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF OLD.status IN ('published','retired') THEN
        IF TG_OP = 'DELETE' THEN
          RAISE EXCEPTION 'PROMPT_VERSION_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        IF ROW(NEW.id,NEW.definition_id,NEW.version,NEW.revision,NEW.content,
               NEW.content_sha256,NEW.variables,NEW.change_description,
               NEW.base_active_version_id,NEW.rollback_from_version_id,NEW.created_at,NEW.published_at)
           IS DISTINCT FROM
           ROW(OLD.id,OLD.definition_id,OLD.version,OLD.revision,OLD.content,
               OLD.content_sha256,OLD.variables,OLD.change_description,
               OLD.base_active_version_id,OLD.rollback_from_version_id,OLD.created_at,OLD.published_at)
           OR NEW.status = 'draft' OR (OLD.status = 'retired' AND NEW.status <> 'retired') THEN
          RAISE EXCEPTION 'PROMPT_VERSION_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER prompt_version_immutable BEFORE UPDATE OR DELETE ON prompt_versions "
        "FOR EACH ROW EXECUTE FUNCTION protect_prompt_version()"
    )
    op.execute("""
    CREATE FUNCTION protect_prompt_dependency() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE root_status text; root_kind text; child_status text; child_kind text; child_hash text;
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        SELECT v.status INTO root_status FROM prompt_versions v
          WHERE v.id=OLD.root_version_id FOR SHARE;
        IF root_status <> 'draft' THEN
          RAISE EXCEPTION 'PROMPT_DEPENDENCY_IMMUTABLE' USING ERRCODE='23514';
        END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      SELECT v.status,d.template_kind INTO root_status,root_kind
        FROM prompt_versions v JOIN prompt_definitions d ON d.id=v.definition_id
        WHERE v.id=NEW.root_version_id FOR SHARE OF v;
      SELECT v.status,d.template_kind,v.content_sha256 INTO child_status,child_kind,child_hash
        FROM prompt_versions v JOIN prompt_definitions d ON d.id=v.definition_id
        WHERE v.id=NEW.dependency_version_id FOR SHARE OF v;
      IF root_status <> 'draft' OR root_kind <> 'task' OR child_kind='task'
         OR child_status NOT IN ('published','retired')
         OR child_hash IS DISTINCT FROM NEW.dependency_sha256 THEN
        RAISE EXCEPTION 'PROMPT_DEPENDENCY_INVALID' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER prompt_dependency_immutable BEFORE INSERT OR UPDATE OR DELETE "
        "ON prompt_version_dependencies FOR EACH ROW EXECUTE FUNCTION protect_prompt_dependency()"
    )
    op.execute("""
    CREATE FUNCTION protect_prompt_suite() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF OLD.status IN ('published','retired') THEN
        IF TG_OP='DELETE' THEN
          RAISE EXCEPTION 'PROMPT_SUITE_IMMUTABLE' USING ERRCODE='23514';
        END IF;
        IF ROW(NEW.id,NEW.agent_key,NEW.scene_key,NEW.version,NEW.cases,NEW.sha256,NEW.model_policy)
           IS DISTINCT FROM
           ROW(OLD.id,OLD.agent_key,OLD.scene_key,OLD.version,OLD.cases,OLD.sha256,OLD.model_policy)
           OR NEW.status='draft' OR (OLD.status='retired' AND NEW.status<>'retired') THEN
          RAISE EXCEPTION 'PROMPT_SUITE_IMMUTABLE' USING ERRCODE='23514';
        END IF;
      END IF;
      IF TG_OP='DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER prompt_suite_immutable BEFORE UPDATE OR DELETE ON prompt_evaluation_suites "
        "FOR EACH ROW EXECUTE FUNCTION protect_prompt_suite()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("fk_prompt_definition_active", "prompt_definitions", type_="foreignkey")
    op.execute("DROP TRIGGER prompt_suite_immutable ON prompt_evaluation_suites")
    op.execute("DROP FUNCTION protect_prompt_suite()")
    op.execute("DROP TRIGGER prompt_dependency_immutable ON prompt_version_dependencies")
    op.execute("DROP FUNCTION protect_prompt_dependency()")
    op.execute("DROP TRIGGER prompt_version_immutable ON prompt_versions")
    op.execute("DROP FUNCTION protect_prompt_version()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_agent_run_prompt_version", "agent_runs", type_="foreignkey")
    op.drop_table("prompt_version_dependencies")
    op.drop_table("prompt_evaluation_runs")
    op.drop_index(
        "uq_prompt_version_published",
        table_name="prompt_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_table("prompt_versions")
    op.drop_table("prompt_evaluation_suites")
    op.drop_table("prompt_audit_events")
    op.drop_table("prompt_definitions")
    # ### end Alembic commands ###
