"""Scoped AI quality cases grants and encrypted snapshots

Revision ID: 20261003_06
Revises: 20261003_05
Create Date: 2026-10-03 17:18:30.565072
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261003_06"
down_revision: str | Sequence[str] | None = "20261003_05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_quality_cases",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_id", sa.Uuid(), nullable=False),
        sa.Column("case_number", sa.String(length=48), nullable=False),
        sa.Column("request_key", sa.Uuid(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("strategy_version", sa.String(length=128), nullable=False),
        sa.Column("trace_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("statement_key_id", sa.String(length=32), nullable=True),
        sa.Column("statement_ciphertext", sa.Text(), nullable=True),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_code", sa.String(length=32), nullable=True),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('submitted','triaging','waiting_user','investigating','resolved','closed')",
            name="ck_quality_case_status",
        ),
        sa.CheckConstraint("version >= 1", name="ck_quality_case_version"),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_number", name="uq_quality_case_number"),
        sa.UniqueConstraint("user_id", "request_key", name="uq_quality_case_request"),
    )
    op.create_index(
        "ix_quality_case_queue", "ai_quality_cases", ["status", "created_at"], unique=False
    )
    op.create_index(
        "uq_quality_active_source",
        "ai_quality_cases",
        ["user_id", "source_type", "source_id", "trace_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.create_table(
        "diagnostic_audits",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_quality_audit_expiry", "diagnostic_audits", ["occurred_at"], unique=False)
    op.create_table(
        "ai_quality_case_events",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("visibility", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=True),
        sa.Column("ciphertext", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["ai_quality_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_quality_case_events_case_id"),
        "ai_quality_case_events",
        ["case_id"],
        unique=False,
    )
    op.create_table(
        "diagnostic_access_grants",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("requester_id", sa.UUID(), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chunk_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','expired','revoked','rejected')",
            name="ck_quality_grant_status",
        ),
        sa.CheckConstraint("version >= 1", name="ck_quality_grant_version"),
        sa.ForeignKeyConstraint(["case_id"], ["ai_quality_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "case_id", name="uq_quality_grant_case"),
    )
    op.create_index(
        "ix_quality_grant_expiry",
        "diagnostic_access_grants",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "diagnostic_replays",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("grant_id", sa.UUID(), nullable=False),
        sa.Column("grant_version", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_key", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["ai_quality_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["grant_id"], ["diagnostic_access_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_replays_case_id"), "diagnostic_replays", ["case_id"], unique=False
    )
    op.create_table(
        "diagnostic_snapshots",
        sa.Column("grant_id", sa.UUID(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["grant_id"], ["diagnostic_access_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grant_id", name="uq_quality_snapshot_grant"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("diagnostic_snapshots")
    op.drop_index(op.f("ix_diagnostic_replays_case_id"), table_name="diagnostic_replays")
    op.drop_table("diagnostic_replays")
    op.drop_index("ix_quality_grant_expiry", table_name="diagnostic_access_grants")
    op.drop_table("diagnostic_access_grants")
    op.drop_index(op.f("ix_ai_quality_case_events_case_id"), table_name="ai_quality_case_events")
    op.drop_table("ai_quality_case_events")
    op.drop_index("ix_quality_audit_expiry", table_name="diagnostic_audits")
    op.drop_table("diagnostic_audits")
    op.drop_index(
        "uq_quality_active_source",
        table_name="ai_quality_cases",
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.drop_index("ix_quality_case_queue", table_name="ai_quality_cases")
    op.drop_table("ai_quality_cases")
    # ### end Alembic commands ###
