"""add file management

Revision ID: 6a1d22048ff8
Revises: 20260825_01
Create Date: 2026-08-26 19:38:02.687669
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6a1d22048ff8"
down_revision: str | Sequence[str] | None = "20260825_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_cleanup_tasks",
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'succeeded', 'failed', 'cancelled')",
            name="ck_file_cleanup_tasks_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_file_cleanup_tasks_idempotency"),
    )
    op.create_index(
        "ix_file_cleanup_tasks_due",
        "file_cleanup_tasks",
        ["status", "next_attempt_at", "priority"],
        unique=False,
    )
    op.create_table(
        "file_orphan_candidates",
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmation_count", sa.Integer(), nullable=False),
        sa.Column("delete_enqueued", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "object_key", name="uq_file_orphan_object"),
    )
    op.create_table(
        "stored_objects",
        sa.Column("storage_domain", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("detected_mime", sa.String(length=128), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('staged', 'validating', 'available', 'deleting', 'deleted', 'missing')",
            name="ck_stored_objects_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
        sa.UniqueConstraint(
            "storage_domain", "sha256", "byte_size", name="uq_stored_object_identity"
        ),
    )
    op.create_index("ix_stored_objects_status", "stored_objects", ["status"], unique=False)
    op.create_table(
        "file_audit_events",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_file_audit_events_occurred", "file_audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_file_audit_events_user", "file_audit_events", ["actor_user_id"], unique=False
    )
    op.create_table(
        "file_policy_versions",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("base_version_id", sa.UUID(), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'retired')", name="ck_file_policy_versions_status"
        ),
        sa.ForeignKeyConstraint(
            ["base_version_id"], ["file_policy_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["published_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_index(
        "uq_file_policy_versions_published",
        "file_policy_versions",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "file_upload_sessions",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("policy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("declared_mime", sa.String(length=128), nullable=True),
        sa.Column("declared_size", sa.BigInteger(), nullable=False),
        sa.Column("client_sha256", sa.String(length=64), nullable=True),
        sa.Column("client_md5", sa.String(length=32), nullable=True),
        sa.Column("upload_mode", sa.String(length=16), nullable=False),
        sa.Column("storage_domain", sa.String(length=32), nullable=False),
        sa.Column("temporary_object_key", sa.String(length=512), nullable=True),
        sa.Column("multipart_upload_id", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("result_knowledge_file_id", sa.UUID(), nullable=True),
        sa.Column("duplicate_file_asset_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('created', 'uploading', 'uploaded', 'verifying', "
            "'duplicate_action_required', 'completed', 'failed', 'cancelled', 'expired')",
            name="ck_file_upload_sessions_status",
        ),
        sa.CheckConstraint(
            "upload_mode IN ('single', 'multipart', 'reuse')", name="ck_upload_mode"
        ),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["policy_version_id"], ["file_policy_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "idempotency_key", name="uq_upload_owner_idempotency"),
    )
    op.create_index(
        "ix_file_upload_sessions_expires_at", "file_upload_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_file_upload_sessions_owner_status",
        "file_upload_sessions",
        ["owner_user_id", "status"],
        unique=False,
    )
    op.create_table(
        "file_assets",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("stored_object_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("detected_mime", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("validation_status", sa.String(length=16), nullable=False),
        sa.Column("validation_failure_code", sa.String(length=64), nullable=True),
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("created_from_upload_session_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "validation_status IN ('staged', 'validating', 'available', 'rejected')",
            name="ck_file_assets_validation_status",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["created_from_upload_session_id"], ["file_upload_sessions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["policy_version_id"], ["file_policy_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["stored_object_id"], ["stored_objects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_file_assets_owner", "file_assets", ["owner_user_id"], unique=False)
    op.create_index(
        "ix_file_assets_stored_object", "file_assets", ["stored_object_id"], unique=False
    )
    op.create_table(
        "knowledge_base_files",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("file_asset_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("processing_failure_code", sa.String(length=64), nullable=True),
        sa.Column("resource_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "processing_status IN ('pending_processing', 'processing', 'succeeded', "
            "'failed', 'cancelled')",
            name="ck_knowledge_base_files_processing_status",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_asset_id"], ["file_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_knowledge_base_files_asset", "knowledge_base_files", ["file_asset_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_base_files_knowledge_base",
        "knowledge_base_files",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        "uq_knowledge_base_files_active_asset",
        "knowledge_base_files",
        ["knowledge_base_id", "file_asset_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_knowledge_base_files_active_asset",
        table_name="knowledge_base_files",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_knowledge_base_files_knowledge_base", table_name="knowledge_base_files")
    op.drop_index("ix_knowledge_base_files_asset", table_name="knowledge_base_files")
    op.drop_table("knowledge_base_files")
    op.drop_index("ix_file_assets_stored_object", table_name="file_assets")
    op.drop_index("ix_file_assets_owner", table_name="file_assets")
    op.drop_table("file_assets")
    op.drop_index("ix_file_upload_sessions_owner_status", table_name="file_upload_sessions")
    op.drop_index("ix_file_upload_sessions_expires_at", table_name="file_upload_sessions")
    op.drop_table("file_upload_sessions")
    op.drop_index(
        "uq_file_policy_versions_published",
        table_name="file_policy_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_table("file_policy_versions")
    op.drop_index("ix_file_audit_events_user", table_name="file_audit_events")
    op.drop_index("ix_file_audit_events_occurred", table_name="file_audit_events")
    op.drop_table("file_audit_events")
    op.drop_index("ix_stored_objects_status", table_name="stored_objects")
    op.drop_table("stored_objects")
    op.drop_table("file_orphan_candidates")
    op.drop_index("ix_file_cleanup_tasks_due", table_name="file_cleanup_tasks")
    op.drop_table("file_cleanup_tasks")
    # ### end Alembic commands ###
