"""version stored object lifecycles

Revision ID: ac3e06160525
Revises: bfa2404e64a1
Create Date: 2026-08-26 20:36:35.663145
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ac3e06160525"
down_revision: str | Sequence[str] | None = "bfa2404e64a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_objects", sa.Column("generation", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stored_objects", "generation")
    # ### end Alembic commands ###
