"""add deletion tombstones and retention support

Revision ID: bfa2404e64a1
Revises: 6a1d22048ff8
Create Date: 2026-08-26 20:29:45.017163
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bfa2404e64a1"
down_revision: str | Sequence[str] | None = "6a1d22048ff8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_deletion_tombstones",
        sa.Column("stored_object_id", sa.UUID(), nullable=False),
        sa.Column("storage_domain", sa.String(length=32), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_object_id", name="uq_file_deletion_tombstone_object"),
    )
    op.create_index(
        "ix_file_deletion_tombstones_deleted_at",
        "file_deletion_tombstones",
        ["deleted_at"],
        unique=False,
    )
    op.alter_column(
        "file_assets", "created_from_upload_session_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("file_assets_created_from_upload_session_id_fkey"), "file_assets", type_="foreignkey"
    )
    op.create_foreign_key(
        "file_assets_created_from_upload_session_id_fkey",
        "file_assets",
        "file_upload_sessions",
        ["created_from_upload_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "file_assets_created_from_upload_session_id_fkey",
        "file_assets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("file_assets_created_from_upload_session_id_fkey"),
        "file_assets",
        "file_upload_sessions",
        ["created_from_upload_session_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "file_assets", "created_from_upload_session_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_index("ix_file_deletion_tombstones_deleted_at", table_name="file_deletion_tombstones")
    op.drop_table("file_deletion_tombstones")
    # ### end Alembic commands ###
